# Generated by Django 6.0.7 on 2026-07-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(help_text='e.g. Issued 2024', max_length=100)),
                ('verify_link', models.URLField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, help_text='Upload certificate PDF/image if available', null=True, upload_to='certifications/')),
                ('color', models.CharField(blank=True, help_text="Tailwind background gradient classes, e.g. 'from-amber-500/10 to-orange-500/10 hover:border-amber-500/30'", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=100)),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one resume can be active at a time.')),
            ],
        ),
    ]
